# Generated by Django 6.0.4 on 2026-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('year_established', models.IntegerField()),
                ('gst_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_size', models.CharField(max_length=100)),
                ('machines', models.IntegerField()),
                ('machine_details', models.TextField()),
                ('production_capacity', models.CharField(max_length=100)),
                ('workers', models.IntegerField()),
                ('quality_process', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('count_gsm', models.CharField(max_length=50)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('colors', models.CharField(max_length=200)),
                ('moq', models.CharField(max_length=50)),
                ('packaging', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('delivery_time', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
