# Generated by Django 6.0.4 on 2026-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
