# Generated by Django 6.0.4 on 2026-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0002_alter_enquiry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='happy_clients',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='monthly_production',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
