# Generated by Django 6.0.4 on 2026-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0003_business_delivery_area_business_happy_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
