# Generated by Django 6.0.4 on 2026-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0006_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
