# Generated by Django 6.0.4 on 2026-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
